# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matrixbest1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 140, 710, 570))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.g02 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g02.setObjectName("g02")
        self.gridLayout.addWidget(self.g02, 0, 2, 1, 1)
        self.g46 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g46.setObjectName("g46")
        self.gridLayout.addWidget(self.g46, 4, 6, 1, 1)
        self.g15 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g15.setObjectName("g15")
        self.gridLayout.addWidget(self.g15, 1, 5, 1, 1)
        self.g08 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g08.setObjectName("g08")
        self.gridLayout.addWidget(self.g08, 0, 8, 1, 1)
        self.g44 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g44.setObjectName("g44")
        self.gridLayout.addWidget(self.g44, 4, 4, 1, 1)
        self.g01 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g01.setObjectName("g01")
        self.gridLayout.addWidget(self.g01, 0, 1, 1, 1)
        self.g68 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g68.setObjectName("g68")
        self.gridLayout.addWidget(self.g68, 6, 8, 1, 1)
        self.g87 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g87.setObjectName("g87")
        self.gridLayout.addWidget(self.g87, 8, 7, 1, 1)
        self.g33 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g33.setObjectName("g33")
        self.gridLayout.addWidget(self.g33, 3, 3, 1, 1)
        self.g84 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g84.setObjectName("g84")
        self.gridLayout.addWidget(self.g84, 8, 4, 1, 1)
        self.g41 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g41.setObjectName("g41")
        self.gridLayout.addWidget(self.g41, 4, 1, 1, 1)
        self.g24 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g24.setObjectName("g24")
        self.gridLayout.addWidget(self.g24, 2, 4, 1, 1)
        self.g45 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g45.setObjectName("g45")
        self.gridLayout.addWidget(self.g45, 4, 5, 1, 1)
        self.g65 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g65.setObjectName("g65")
        self.gridLayout.addWidget(self.g65, 6, 5, 1, 1)
        self.g81 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g81.setObjectName("g81")
        self.gridLayout.addWidget(self.g81, 8, 1, 1, 1)
        self.g70 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g70.setObjectName("g70")
        self.gridLayout.addWidget(self.g70, 7, 0, 1, 1)
        self.g62 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g62.setObjectName("g62")
        self.gridLayout.addWidget(self.g62, 6, 2, 1, 1)
        self.g71 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g71.setObjectName("g71")
        self.gridLayout.addWidget(self.g71, 7, 1, 1, 1)
        self.g78 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g78.setObjectName("g78")
        self.gridLayout.addWidget(self.g78, 7, 8, 1, 1)
        self.g47 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g47.setObjectName("g47")
        self.gridLayout.addWidget(self.g47, 4, 7, 1, 1)
        self.g48 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g48.setObjectName("g48")
        self.gridLayout.addWidget(self.g48, 4, 8, 1, 1)
        self.g72 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g72.setObjectName("g72")
        self.gridLayout.addWidget(self.g72, 7, 2, 1, 1)
        self.g67 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g67.setObjectName("g67")
        self.gridLayout.addWidget(self.g67, 6, 7, 1, 1)
        self.g66 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g66.setObjectName("g66")
        self.gridLayout.addWidget(self.g66, 6, 6, 1, 1)
        self.g18 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g18.setObjectName("g18")
        self.gridLayout.addWidget(self.g18, 1, 8, 1, 1)
        self.g60 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g60.setObjectName("g60")
        self.gridLayout.addWidget(self.g60, 6, 0, 1, 1)
        self.g16 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g16.setObjectName("g16")
        self.gridLayout.addWidget(self.g16, 1, 6, 1, 1)
        self.g61 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g61.setObjectName("g61")
        self.gridLayout.addWidget(self.g61, 6, 1, 1, 1)
        self.g63 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g63.setObjectName("g63")
        self.gridLayout.addWidget(self.g63, 6, 3, 1, 1)
        self.g10 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g10.setObjectName("g10")
        self.gridLayout.addWidget(self.g10, 1, 0, 1, 1)
        self.g85 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g85.setObjectName("g85")
        self.gridLayout.addWidget(self.g85, 8, 5, 1, 1)
        self.g12 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g12.setObjectName("g12")
        self.gridLayout.addWidget(self.g12, 1, 2, 1, 1)
        self.g52 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g52.setObjectName("g52")
        self.gridLayout.addWidget(self.g52, 5, 2, 1, 1)
        self.g32 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g32.setObjectName("g32")
        self.gridLayout.addWidget(self.g32, 3, 2, 1, 1)
        self.g76 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g76.setObjectName("g76")
        self.gridLayout.addWidget(self.g76, 7, 6, 1, 1)
        self.g23 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g23.setObjectName("g23")
        self.gridLayout.addWidget(self.g23, 2, 3, 1, 1)
        self.g28 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g28.setObjectName("g28")
        self.gridLayout.addWidget(self.g28, 2, 8, 1, 1)
        self.g53 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g53.setObjectName("g53")
        self.gridLayout.addWidget(self.g53, 5, 3, 1, 1)
        self.g17 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g17.setObjectName("g17")
        self.gridLayout.addWidget(self.g17, 1, 7, 1, 1)
        self.g77 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g77.setObjectName("g77")
        self.gridLayout.addWidget(self.g77, 7, 7, 1, 1)
        self.g83 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g83.setObjectName("g83")
        self.gridLayout.addWidget(self.g83, 8, 3, 1, 1)
        self.g73 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g73.setObjectName("g73")
        self.gridLayout.addWidget(self.g73, 7, 3, 1, 1)
        self.g03 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g03.setObjectName("g03")
        self.gridLayout.addWidget(self.g03, 0, 3, 1, 1)
        self.g27 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g27.setObjectName("g27")
        self.gridLayout.addWidget(self.g27, 2, 7, 1, 1)
        self.g14 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g14.setObjectName("g14")
        self.gridLayout.addWidget(self.g14, 1, 4, 1, 1)
        self.g54 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g54.setObjectName("g54")
        self.gridLayout.addWidget(self.g54, 5, 4, 1, 1)
        self.g07 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g07.setObjectName("g07")
        self.gridLayout.addWidget(self.g07, 0, 7, 1, 1)
        self.g37 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g37.setObjectName("g37")
        self.gridLayout.addWidget(self.g37, 3, 7, 1, 1)
        self.g35 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g35.setObjectName("g35")
        self.gridLayout.addWidget(self.g35, 3, 5, 1, 1)
        self.g57 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g57.setObjectName("g57")
        self.gridLayout.addWidget(self.g57, 5, 7, 1, 1)
        self.g86 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g86.setObjectName("g86")
        self.gridLayout.addWidget(self.g86, 8, 6, 1, 1)
        self.g88 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g88.setObjectName("g88")
        self.gridLayout.addWidget(self.g88, 8, 8, 1, 1)
        self.g51 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g51.setObjectName("g51")
        self.gridLayout.addWidget(self.g51, 5, 1, 1, 1)
        self.g04 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g04.setObjectName("g04")
        self.gridLayout.addWidget(self.g04, 0, 4, 1, 1)
        self.g40 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g40.setObjectName("g40")
        self.gridLayout.addWidget(self.g40, 4, 0, 1, 1)
        self.g56 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g56.setObjectName("g56")
        self.gridLayout.addWidget(self.g56, 5, 6, 1, 1)
        self.g22 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g22.setObjectName("g22")
        self.gridLayout.addWidget(self.g22, 2, 2, 1, 1)
        self.g05 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g05.setObjectName("g05")
        self.gridLayout.addWidget(self.g05, 0, 5, 1, 1)
        self.g20 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g20.setObjectName("g20")
        self.gridLayout.addWidget(self.g20, 2, 0, 1, 1)
        self.g75 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g75.setObjectName("g75")
        self.gridLayout.addWidget(self.g75, 7, 5, 1, 1)
        self.g74 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g74.setObjectName("g74")
        self.gridLayout.addWidget(self.g74, 7, 4, 1, 1)
        self.g55 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g55.setObjectName("g55")
        self.gridLayout.addWidget(self.g55, 5, 5, 1, 1)
        self.g38 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g38.setObjectName("g38")
        self.gridLayout.addWidget(self.g38, 3, 8, 1, 1)
        self.g64 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g64.setObjectName("g64")
        self.gridLayout.addWidget(self.g64, 6, 4, 1, 1)
        self.g26 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g26.setObjectName("g26")
        self.gridLayout.addWidget(self.g26, 2, 6, 1, 1)
        self.g80 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g80.setObjectName("g80")
        self.gridLayout.addWidget(self.g80, 8, 0, 1, 1)
        self.g30 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g30.setObjectName("g30")
        self.gridLayout.addWidget(self.g30, 3, 0, 1, 1)
        self.g06 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g06.setObjectName("g06")
        self.gridLayout.addWidget(self.g06, 0, 6, 1, 1)
        self.g11 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g11.setObjectName("g11")
        self.gridLayout.addWidget(self.g11, 1, 1, 1, 1)
        self.g82 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g82.setObjectName("g82")
        self.gridLayout.addWidget(self.g82, 8, 2, 1, 1)
        self.g43 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g43.setObjectName("g43")
        self.gridLayout.addWidget(self.g43, 4, 3, 1, 1)
        self.g31 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g31.setObjectName("g31")
        self.gridLayout.addWidget(self.g31, 3, 1, 1, 1)
        self.g50 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g50.setObjectName("g50")
        self.gridLayout.addWidget(self.g50, 5, 0, 1, 1)
        self.g36 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g36.setObjectName("g36")
        self.gridLayout.addWidget(self.g36, 3, 6, 1, 1)
        self.g13 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g13.setObjectName("g13")
        self.gridLayout.addWidget(self.g13, 1, 3, 1, 1)
        self.g34 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g34.setObjectName("g34")
        self.gridLayout.addWidget(self.g34, 3, 4, 1, 1)
        self.g58 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g58.setObjectName("g58")
        self.gridLayout.addWidget(self.g58, 5, 8, 1, 1)
        self.g42 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g42.setObjectName("g42")
        self.gridLayout.addWidget(self.g42, 4, 2, 1, 1)
        self.g25 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g25.setObjectName("g25")
        self.gridLayout.addWidget(self.g25, 2, 5, 1, 1)
        self.g21 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g21.setObjectName("g21")
        self.gridLayout.addWidget(self.g21, 2, 1, 1, 1)
        self.g00 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.g00.setObjectName("g00")
        self.gridLayout.addWidget(self.g00, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 40, 181, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton.clicked.connect(self,clicked)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def clicked(self):
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SUDOKU"))
        self.pushButton.setText(_translate("MainWindow", "SOLVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
